[tool.poetry]
name = "draft-game-api"
version = "0.1.0"
description = ""
authors = ["Adam Gleason <adam.g.gleason@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.8"
uvicorn = "^0.34.0"
sqlalchemy = "^2.0.38"
python-dotenv = "^1.0.1"
psycopg2-binary = "^2.9.10"
python-slugify = "^8.0.4"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.6"
poetry-plugin-export = "^1.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "C", "N", "Q", "B", "A"]
ignore = ["E501"]
