# Generated by Django 4.2.13 on 2024-05-08 03:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(help_text='Card Type label', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Card Type',
                'verbose_name_plural': 'Card Types',
            },
        ),
        migrations.CreateModel(
            name='EffectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(help_text='Effect Type label', max_length=255)),
                ('cost', models.CharField(blank=True, help_text='Effect Cost', max_length=50)),
            ],
            options={
                'verbose_name': 'Effect Type',
                'verbose_name_plural': 'Effect Types',
                'unique_together': {('label', 'cost')},
            },
        ),
        migrations.CreateModel(
            name='CardEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('effect_text', models.CharField(help_text='Card Effect text description', max_length=1000)),
                ('effect_types', models.ManyToManyField(help_text='Card Effect - Effect Type relation', related_name='effect_type', to='cards.effecttype')),
            ],
            options={
                'verbose_name': 'Card Effect',
                'verbose_name_plural': 'Card Effects',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of Card', max_length=255, unique=True)),
                ('value', models.SmallIntegerField(help_text='Point value of Card')),
                ('card_type', models.ForeignKey(help_text='Card - Card Type relation', on_delete=django.db.models.deletion.PROTECT, related_name='card_type', to='cards.cardtype')),
                ('effect', models.ForeignKey(help_text='Card - Card Effect relation', on_delete=django.db.models.deletion.PROTECT, related_name='card_effect', to='cards.cardeffect')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
